# ============================================================================
# Object Definitions (物件定義與預設值)
# Based on all_att.txt
# ============================================================================

watchBackground = [{"TYPE": "imageLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 512,  "description": "Width"},
    {"Height": 512,  "description": "Height"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Tint": "ffffff",  "description": "Tint color"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Custom image": "",  "description": "Custom image file"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},]


# Text (文字)
text = [
    {"TYPE": "textLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Text": "",  "description": "Text content"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Animation": {
        "Display": "None",
        "Animation in": "None",
        "Delay start": 0,
        "Duration in": 0.5,
        "Duration on": 0.5,
        "Animation out": "None",
        "Duration out": 0.5,
        "Duration off": 0.5,
        "Repeat count": 1,
        "Restart on load": True,
        "Restart on bright": True,
        "Restart on text change": True,
    },  "description": "Animation settings"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Font name"},
    {"Text size": 40,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Light (方向光源)
light = [
    {"TYPE": "directionalLightLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Enable": True,  "description": "Enable light"},
    {"Intensity": 150,  "description": "Light intensity"},
    {"Direction X": 0,  "description": "X direction"},
    {"Direction Y": 0,  "description": "Y direction"},
    {"Direction Z": -100,  "description": "Z direction"},
    {"Color": "ffffff",  "description": "Light color"},
]

# Photo Cube (3D照片立方體)
photoCube = [
    {"TYPE": "3DLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Photo": "",  "description": "Photo/model file"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Z": 260,  "description": "Z coordinate"},
    {"Rotation X": "-50-{c_elapsed}*4",  "description": "X-axis rotation"},
    {"Rotation Y": "-50-{c_elapsed}*7",  "description": "Y-axis rotation"},
    {"Rotation Z": "30-{c_elapsed}*10",  "description": "Z-axis rotation"},
    {"Scale X": 350,  "description": "X-axis scale"},
    {"Scale Y": 350,  "description": "Y-axis scale"},
    {"Scale Z": 350,  "description": "Z-axis scale"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Color": "ffffff",  "description": "Color"},
    {"Display": "Always",  "description": "Display mode"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Text Curved (曲線文字) - inherits from text
textCurved = [
    {"TYPE": "curvedTextLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Text": "",  "description": "Text content"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Font name"},
    {"Text size": 40,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
    {"Radius": 200,  "description": "Curve radius"},
    {"Direction": "Up",  "description": "Curve direction"},
]

# Minute Hand (分針圖片)
minuteHand = [
    {"TYPE": "imageLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 512,  "description": "Width"},
    {"Height": 512,  "description": "Height"},
    {"Rotation": "{drm}",  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Tint": "ffffff",  "description": "Tint color"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Custom image": "",  "description": "Custom image file"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Hour Hand (時針圖片) - inherits from minuteHand
hourHand = [
    {"TYPE": "imageLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 512,  "description": "Width"},
    {"Height": 512,  "description": "Height"},
    {"Rotation": "{drh}",  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Tint": "ffffff",  "description": "Tint color"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Custom image": "",  "description": "Custom image file"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Second Hand (秒針圖片) - inherits from minuteHand
secondHand = [
    {"TYPE": "imageLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 512,  "description": "Width"},
    {"Height": 512,  "description": "Height"},
    {"Rotation": "{drs}",  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Tint": "ffffff",  "description": "Tint color"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Custom image": "",  "description": "Custom image file"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Battery (電池圖示)
battery = [
    {"TYPE": "imageCondLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 80,  "description": "Width"},
    {"Height": 80,  "description": "Height"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Tint": "ffffff",  "description": "Tint color"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Image selection": "'{bc}' == 'Charging' and 7 or {bl} >= 90 and 1 or {bl} >= 70 and 2 or {bl} >= 50 and 3 or {bl} >= 30 and 4 or {bl} >= 10 and 5 or 6",  "description": "Image selection expression"},
    {"Image grid": "3x3",  "description": "Image grid layout"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Custom image": "",  "description": "Custom image file"},
    {"Weather includes night symbols": True,  "description": "Include night weather symbols"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Wifi (Wifi訊號圖示) - inherits from battery
wifi = [
    {"TYPE": "imageCondLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 60,  "description": "Width"},
    {"Height": 60,  "description": "Height"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Tint": "ffffff",  "description": "Tint color"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Image selection": "{pws} >= 0.86 and 1 or {pws} >= 0.62 and 2 or {pws} >= 0.37 and 3 or {pws} >= 0.12 and 4 or 5",  "description": "Image selection expression"},
    {"Image grid": "3x2",  "description": "Image grid layout"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Custom image": "",  "description": "Custom image file"},
    {"Weather includes night symbols": True,  "description": "Include night weather symbols"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Event (事件文字) - inherits from text
event = [
    {"TYPE": "textLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Text": "",  "description": "Text content"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": -120,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Font name"},
    {"Text size": 30,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Countdown (倒數計時) - inherits from text
countdown = [
    {"TYPE": "textLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Text": "",  "description": "Text content"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 28,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Font name"},
    {"Text size": 50,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Tachy (測速計)
tachy = [
    {"TYPE": "tachymeterLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Text": "TACHYMETER",  "description": "Title text"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "BebasNeue",  "description": "Font name"},
    {"Text size": 25,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Radius": 230,  "description": "Radius"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Marker width": 10,  "description": "Marker width"},
    {"Marker height": 10,  "description": "Marker height"},
    {"Major markers": "Medium",  "description": "Major markers style"},
    {"Minor markers": "Medium",  "description": "Minor markers style"},
    {"Speeds": "400,300,240,200,180,160,140,120,110,95,90,85,80,75,70,65,60",  "description": "Speed values"},
    {"Text rotation": "Rotate Upright",  "description": "Text rotation"},
    {"Squarify": 0,  "description": "Squarify for square watches"},
    {"Display": "Always",  "description": "Display mode"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Weather (天氣圖示) - inherits from battery
weather = [
    {"TYPE": "imageCondLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 256,  "description": "Width"},
    {"Height": 256,  "description": "Height"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Tint": "ffffff",  "description": "Tint color"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Image selection": "'{wci}' == '01d' and 1 or '{wci}' == '02d' and 2 or '{wci}' == '03d' and 3 or '{wci}' == '04d' and 4 or '{wci}' == '09d' and 5 or '{wci}' == '10d' and 6 or '{wci}' == '11d' and 7 or '{wci}' == '13d' and 8 or '{wci}' == '50d' and 9 or 1",  "description": "Image selection expression"},
    {"Image grid": "3x3",  "description": "Image grid layout"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Custom image": "",  "description": "Custom image file"},
    {"Weather includes night symbols": True,  "description": "Include night weather symbols"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Shape (形狀)
shape = [
    {"TYPE": "shapeLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Shape": "square",  "description": "Shape type"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 100,  "description": "Width"},
    {"Height": 100,  "description": "Height"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "center",  "description": "Alignment"},
    {"Color": "#ffffff",  "description": "Fill color"},
    {"Display": "always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Shape effect": "None",  "description": "Shape effect"},
]

# Marker (標記)
marker = [
    {"TYPE": "markerLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Text": "TACHYMETER",  "description": "Title text"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "BebasNeue",  "description": "Font name"},
    {"Text size": 25,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Radius": 256,  "description": "Radius"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Marker width": 10,  "description": "Marker width"},
    {"Marker height": 35,  "description": "Marker height"},
    {"Marker count": 12,  "description": "Marker count"},
    {"Squarify": 0,  "description": "Squarify for square watches"},
    {"Display": "Always",  "description": "Display mode"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
]

# Map (地圖)
map = [
    {"TYPE": "mapLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 512,  "description": "Width"},
    {"Height": 512,  "description": "Height"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Latitude": "{alat}",  "description": "Latitude"},
    {"Longitude": "{alon}",  "description": "Longitude"},
    {"Map zoom": 16,  "description": "Map zoom level"},
    {"Map scale": 100,  "description": "Map scale"},
    {"Tint": "ffffff",  "description": "Tint color"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Display": "Bright only",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Map effect": "None",  "description": "Map effect"},
]

# Compass (指南針)
compass = [
    {"TYPE": "imageLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 200,  "description": "Width"},
    {"Height": 200,  "description": "Height"},
    {"Rotation": "{src}",  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Tint": "ffffff",  "description": "Tint color"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Display": "Bright only",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Custom image": "",  "description": "Custom image file"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Date (日期文字)
date = [
    {"TYPE": "textLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Text": "{ddw} {dnnn} {dd}",  "description": "Text content"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 120,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Font name"},
    {"Text size": 40,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Steps (步數文字)
steps = [
    {"TYPE": "textLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Text": "{ssc}",  "description": "Text content"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 30,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Font name"},
    {"Text size": 40,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Moon (月相圖示)
moon = [
    {"TYPE": "imageCondLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 80,  "description": "Width"},
    {"Height": 80,  "description": "Height"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Tint": "ffffff",  "description": "Tint color"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Image selection": "{wmp}",  "description": "Image selection expression"},
    {"Image grid": "3x3",  "description": "Image grid layout"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Custom image": "",  "description": "Custom image file"},
    {"Weather includes night symbols": True,  "description": "Include night weather symbols"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# 3D (3D模型)
model3d = [
    {"TYPE": "3DLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Z": 0,  "description": "Z coordinate"},
    {"Rotation X": 0,  "description": "X-axis rotation"},
    {"Rotation Y": 0,  "description": "Y-axis rotation"},
    {"Rotation Z": 0,  "description": "Z-axis rotation"},
    {"Scale X": 40,  "description": "X-axis scale"},
    {"Scale Y": 40,  "description": "Y-axis scale"},
    {"Scale Z": 40,  "description": "Z-axis scale"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Color": "ffffff",  "description": "Color"},
    {"Display": "Always",  "description": "Display mode"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Slideshow (幻燈片)
slideshow = [
    {"TYPE": "slideshowLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Photo": "",  "description": "Photo files"},
    {"Photo duration": 5,  "description": "Photo display duration"},
    {"Photo clip": "corner1",  "description": "Photo clip style"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 300,  "description": "Width"},
    {"Height": 300,  "description": "Height"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Tint": "ffffff",  "description": "Tint color"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Numbers (環形數字)
numbers = [
    {"TYPE": "textRingLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Font name"},
    {"Text size": 30,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Always",  "description": "Display mode"},
    {"Radius": 200,  "description": "Ring radius"},
    {"Ring type": "1-12",  "description": "Ring type"},
    {"Show every": 1,  "description": "Show every N items"},
    {"Hide text": "",  "description": "Text to hide"},
    {"Text rotation": "Upright",  "description": "Text rotation style"},
    {"Angle start": 0,  "description": "Start angle"},
    {"Angle end": 360,  "description": "End angle"},
    {"Squarify": 0,  "description": "Squarify for square watches"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Hour Min Markers (時分標記)
hourMinMarkers = [
    {"TYPE": "markersHMLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Radius": 256,  "description": "Radius"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Hour markers": "Medium",  "description": "Hour markers style"},
    {"Minute markers": "Medium",  "description": "Minute markers style"},
    {"Hour color": "ffffff",  "description": "Hour markers color"},
    {"Minute color": "ffffff",  "description": "Minute markers color"},
    {"Squarify": 0,  "description": "Squarify for square watches"},
    {"Display": "Always",  "description": "Display mode"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Rounded (圓角矩形)
rounded = [
    {"TYPE": "roundedRectangleLayer"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Width": 300,  "description": "Width"},
    {"Height": 200,  "description": "Height"},
    {"Corner radius": 50,  "description": "Corner radius"},
    {"Corner type": 1,  "description": "Corner type"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "center",  "description": "Alignment"},
    {"Color": "#ffffff",  "description": "Fill color"},
    {"Display": "always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Shape effect": "None",  "description": "Shape effect"},
]

# Series (數據系列)
series = [
    {"TYPE": "seriesLayer"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Primary font"},
    {"Font 2": "Roboto-Regular",  "description": "Secondary font"},
    {"Text size": 30,  "description": "Primary font size"},
    {"Text size 2": 20,  "description": "Secondary font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color 2": "888888",  "description": "Secondary color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Always",  "description": "Display mode"},
    {"Series type": "Day of the week short",  "description": "Series type"},
    {"Orientation": "Vertical",  "description": "Orientation"},
    {"Current position": "Current Centered",  "description": "Current position"},
    {"Spacing": 10,  "description": "Spacing"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Time (時間文字)
time = [
    {"TYPE": "textLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Text": "{dh23z}:{dmz}",  "description": "Text content"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Font name"},
    {"Text size": 100,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Stopwatch 1 (碼錶時間)
stopWatch1 = [
    {"TYPE": "textLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Text": "{swm}:{sws}:{swsss}",  "description": "Text content"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Font name"},
    {"Text size": 36,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "None",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Stopwatch 2 (碼錶開始/停止)
stopWatch2 = [
    {"TYPE": "textLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Text": "{swr} and 'STOP' or 'START'",  "description": "Text content"},
    {"X": -100,  "description": "X coordinate"},
    {"Y": 100,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Font name"},
    {"Text size": 20,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "Stopwatch Start/Stop",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Stopwatch 3 (碼錶重設)
stopWatch3 = [
    {"TYPE": "textLayer"},
    {"Name": "Layer+id",  "description": "Layer name"},
    {"Text": "RESET",  "description": "Text content"},
    {"X": 100,  "description": "X coordinate"},
    {"Y": 100,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Font name"},
    {"Text size": 20,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Always",  "description": "Display mode"},
    {"Shader": "None",  "description": "Shader type"},
    {"Tap action": "Stopwatch Reset",  "description": "Tap action"},
    {"Text effect": "None",  "description": "Text effect"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Complication (複雜功能)
complication = [
    {"TYPE": "complicationLayer"},
    {"Color text": "#b3b3b3",  "description": "Text color"},
    {"Color background": "#494949",  "description": "Background color"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Font": "Roboto-Regular",  "description": "Font name"},
    {"Text size": 25,  "description": "Font size"},
    {"Color": "ffffff",  "description": "Primary color"},
    {"Color dim": "ffffff",  "description": "Dim mode color"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Width": 100,  "description": "Width"},
    {"Height": 100,  "description": "Height"},
    {"Alignment": "Center",  "description": "Alignment"},
    {"Transform": "None",  "description": "Text transform"},
    {"Display": "Bright only",  "description": "Display mode"},
    {"Keep position if card displayed": False,  "description": "Keep position if card displayed"},
]

# Chart (圖表)
chart = [
    {"TYPE": "chartLayer"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Width": 205,  "description": "Width"},
    {"Height": 76,  "description": "Height"},
    {"Color": "#ffffff",  "description": "Primary color"},
    {"Color 2": "#9e9e9e",  "description": "Secondary color"},
    {"Color 3": "#ffffff",  "description": "Tertiary color"},
    {"Color 4": "#ffffff",  "description": "Quaternary color"},
    {"Chart type": "line",  "description": "Chart type"},
    {"Data points": "",  "description": "Data points"},
    {"Min max": "",  "description": "Min/Max values"},
    {"Chart group": 0,  "description": "Chart group"},
    {"Line width": 4,  "description": "Line width"},
    {"Marker size": 11,  "description": "Marker size"},
    {"Tension": 0,  "description": "Line tension"},
    {"Top opacity": 42,  "description": "Top opacity"},
    {"Bottom opacity": 0,  "description": "Bottom opacity"},
    {"Radius": 100,  "description": "Corner radius"},
    {"Bar thickness": 67,  "description": "Bar thickness"},
    {"Corner type": 1,  "description": "Corner type"},
    {"Lines": "",  "description": "Lines config"},
    {"Labels": "",  "description": "Labels config"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Display": "bd",  "description": "Display mode"},
]

# Image GIF (GIF動圖)
imageGif = [
    {"TYPE": "imageGifLayer"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Alignment": "cc",  "description": "Alignment"},
    {"Path": "",  "description": "Image path"},
    {"Width": 100,  "description": "Width"},
    {"Height": 100,  "description": "Height"},
    {"Gif delay": 100,  "description": "GIF frame delay"},
    {"Display": "bd",  "description": "Display mode"},
]

# Progress (進度條)
progress = [
    {"TYPE": "progressLayer"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Width": 114,  "description": "Width"},
    {"Height": 24,  "description": "Height"},
    {"Color": "#dddddd",  "description": "Primary color"},
    {"Color 2": "#dddddd",  "description": "Secondary color"},
    {"Color 3": "#525151",  "description": "Background color"},
    {"Color 4": "#3c3b3b",  "description": "Background secondary color"},
    {"Outside opacity": 100,  "description": "Outside opacity"},
    {"Radius": 0,  "description": "Corner radius"},
    {"Pct complete": "{bl}",  "description": "Percent complete expression"},
    {"Angle": 90,  "description": "Angle"},
    {"Margin": 0,  "description": "Margin"},
    {"End style": "flat",  "description": "End style"},
    {"Corner type": 1,  "description": "Corner type"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Display": "bd",  "description": "Display mode"},
]

# Ring (圓環)
ring = [
    {"TYPE": "ringLayer"},
    {"X": 0,  "description": "X coordinate"},
    {"Y": 0,  "description": "Y coordinate"},
    {"Gyro effect": 0,  "description": "Gyroscope effect"},
    {"Rotation": 0,  "description": "Rotation angle"},
    {"Skew X": 0,  "description": "X-axis skew"},
    {"Skew Y": 0,  "description": "Y-axis skew"},
    {"Opacity": 100,  "description": "Opacity"},
    {"Radius outer": 57,  "description": "Outer radius"},
    {"Radius inner": 53,  "description": "Inner radius"},
    {"Radius": 100,  "description": "Corner radius"},
    {"Angle": 0,  "description": "Current angle"},
    {"Angle total": 360,  "description": "Total angle"},
    {"Is clockwise": "Y",  "description": "Clockwise direction"},
    {"Color": "#ffffff",  "description": "Primary color"},
    {"Color 2": "#ffffff",  "description": "Secondary color"},
    {"Color 3": "#626262",  "description": "Background color"},
    {"Outside opacity": 100,  "description": "Outside opacity"},
    {"Anim scale X": 100,  "description": "Animation scale X"},
    {"Anim scale Y": 100,  "description": "Animation scale Y"},
    {"Display": "bd",  "description": "Display mode"},
]

# Export all object definitions
__all__ = [
    "watchBackground",
    'text',
    'light',
    'photoCube',
    'textCurved',
    'minuteHand',
    'hourHand',
    'secondHand',
    'battery',
    'wifi',
    'event',
    'countdown',
    'tachy',
    'weather',
    'shape',
    'marker',
    'map',
    'compass',
    'date',
    'steps',
    'moon',
    'model3d',
    'slideshow',
    'numbers',
    'hourMinMarkers',
    'rounded',
    'series',
    'time',
    'stopWatch1',
    'stopWatch2',
    'stopWatch3',
    'complication',
    'chart',
    'imageGif',
    'progress',
    'ring',
]
